#!/usr/bin/env bash

set -euo pipefail

readonly CONFIG_ROOT="${XDG_CONFIG_HOME:-${HOME}/.config}/file-upload"
readonly CONFIG_FILE="${FILE_UPLOAD_CONFIG:-${CONFIG_ROOT}/config}"
readonly VERCEL_PROJECT_DIR="${CONFIG_ROOT}/vercel-project"
readonly VERCEL_RUNTIME_DIR="${CONFIG_ROOT}/runtime"
readonly BLOB_ENV_FILE="${VERCEL_PROJECT_DIR}/.env.local"
readonly VERCEL_CLI_VERSION="59.1.4"

usage() {
  cat <<'EOF'
Usage:
  upload.sh --configure
  upload.sh <path-to-file> [more-files...]

Optional environment variables:
  FILE_UPLOAD_BASE_URL  Override the configured public base URL.
  FILE_UPLOAD_CONFIG    Override the configuration file path.
EOF
}

configure() {
  local base_url

  printf 'Public base URL (for example, https://files.example.com): '
  read -r base_url
  base_url="${base_url%/}"

  if [[ ! "${base_url}" =~ ^https://[^/]+$ ]]; then
    printf 'Error: enter an HTTPS origin without a path.\n' >&2
    exit 1
  fi

  umask 077
  mkdir -p "${CONFIG_ROOT}" "${VERCEL_PROJECT_DIR}" "${VERCEL_RUNTIME_DIR}"
  printf 'FILE_UPLOAD_BASE_URL=%q\n' "${base_url}" > "${CONFIG_FILE}"

  printf '\nLink the Vercel project that owns the Blob store.\n'
  npx --yes "vercel@${VERCEL_CLI_VERSION}" link --cwd "${VERCEL_PROJECT_DIR}"
  npx --yes "vercel@${VERCEL_CLI_VERSION}" env pull "${BLOB_ENV_FILE}" \
    --yes \
    --environment development \
    --cwd "${VERCEL_PROJECT_DIR}"
  chmod 600 "${CONFIG_FILE}" "${BLOB_ENV_FILE}"

  if ! grep -q '^BLOB_READ_WRITE_TOKEN=' "${BLOB_ENV_FILE}"; then
    printf 'Error: the linked project does not expose BLOB_READ_WRITE_TOKEN.\n' >&2
    exit 1
  fi

  printf '\nConfiguration saved in %s\n' "${CONFIG_ROOT}"
}

load_config() {
  if [[ -f "${CONFIG_FILE}" ]]; then
    # The file is created by this script with shell-escaped values and mode 600.
    # shellcheck disable=SC1090
    source "${CONFIG_FILE}"
  fi

  if [[ -z "${FILE_UPLOAD_BASE_URL:-}" ]]; then
    printf 'Error: file upload is not configured. Run %s --configure.\n' "$0" >&2
    exit 1
  fi

  FILE_UPLOAD_BASE_URL="${FILE_UPLOAD_BASE_URL%/}"

  if [[ ! -f "${BLOB_ENV_FILE}" ]]; then
    printf 'Error: the Vercel Blob credentials are missing. Run %s --configure.\n' "$0" >&2
    exit 1
  fi

  set -a
  # The file is generated by `vercel env pull` and stored with mode 600.
  # shellcheck disable=SC1090
  source "${BLOB_ENV_FILE}"
  set +a

  if [[ -z "${BLOB_READ_WRITE_TOKEN:-}" ]]; then
    printf 'Error: BLOB_READ_WRITE_TOKEN is missing. Run %s --configure.\n' "$0" >&2
    exit 1
  fi

  # Prefer the Blob read-write token. Recent Vercel CLI versions also pull an
  # OIDC token, which requires a store id and conflicts with token auth.
  unset VERCEL_OIDC_TOKEN BLOB_STORE_ID
  mkdir -p "${VERCEL_RUNTIME_DIR}"
}

absolute_path() {
  local file="$1"
  printf '%s/%s' "$(cd "$(dirname "${file}")" && pwd -P)" "$(basename "${file}")"
}

slugify() {
  local value="${1%.*}"
  value="$(printf '%s' "${value}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g')"
  printf '%s' "${value:-file}"
}

object_key() {
  local file="$1"
  local basename extension slug suffix

  basename="$(basename "${file}")"
  extension=""
  if [[ "${basename}" == *.* && "${basename}" != .* ]]; then
    extension=".${basename##*.}"
  fi

  slug="$(slugify "${basename}")"
  suffix="$(node -e "process.stdout.write(require('node:crypto').randomBytes(6).toString('hex'))")"
  printf '%s/%s-%s%s' "$(date -u +%Y/%m/%d)" "${slug}" "${suffix}" "${extension}"
}

upload() {
  local file="$1"
  local absolute_file key content_type upload_output

  if [[ ! -f "${file}" ]]; then
    printf 'Error: file not found: %s\n' "${file}" >&2
    return 1
  fi

  absolute_file="$(absolute_path "${file}")"
  key="$(object_key "${absolute_file}")"
  content_type="$(file --brief --mime-type "${absolute_file}")"

  if ! upload_output="$(
    npx --yes "vercel@${VERCEL_CLI_VERSION}" blob put "${absolute_file}" \
      --cwd "${VERCEL_RUNTIME_DIR}" \
      --access public \
      --pathname "${key}" \
      --content-type "${content_type}" \
      --cache-control-max-age 31536000 \
      --multipart true \
      --non-interactive \
      --no-color 2>&1
  )"; then
    printf '%s\n' "${upload_output}" >&2
    return 1
  fi

  printf '%s/%s\n' "${FILE_UPLOAD_BASE_URL}" "${key}"
}

main() {
  if [[ "${1:-}" == "--configure" ]]; then
    configure
    exit 0
  fi

  if [[ $# -eq 0 || "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    usage
    exit 0
  fi

  load_config

  local file
  for file in "$@"; do
    upload "${file}"
  done
}

main "$@"
